# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrequest.proto\"\x80\x01\n\x03RFW\x12\x0e\n\x06rfw_id\x18\x01 \x02(\t\x12\x16\n\x0e\x62\x65nchmark_type\x18\x02 \x02(\t\x12\x17\n\x0fworkload_metric\x18\x03 \x02(\t\x12\x12\n\nbatch_unit\x18\x04 \x02(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x02(\x05\x12\x12\n\nbatch_size\x18\x06 \x02(\x05')



_RFW = DESCRIPTOR.message_types_by_name['RFW']
RFW = _reflection.GeneratedProtocolMessageType('RFW', (_message.Message,), {
  'DESCRIPTOR' : _RFW,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:RFW)
  })
_sym_db.RegisterMessage(RFW)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RFW._serialized_start=18
  _RFW._serialized_end=146
# @@protoc_insertion_point(module_scope)
