# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\"=\n\x03RFD\x12\x0e\n\x06rfw_id\x18\x01 \x02(\t\x12\x15\n\rlast_batch_id\x18\x02 \x02(\x05\x12\x0f\n\x07samples\x18\x03 \x03(\t')



_RFD = DESCRIPTOR.message_types_by_name['RFD']
RFD = _reflection.GeneratedProtocolMessageType('RFD', (_message.Message,), {
  'DESCRIPTOR' : _RFD,
  '__module__' : 'response_pb2'
  # @@protoc_insertion_point(class_scope:RFD)
  })
_sym_db.RegisterMessage(RFD)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RFD._serialized_start=18
  _RFD._serialized_end=79
# @@protoc_insertion_point(module_scope)
